services:
  - type: web
    name: ta-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server.app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /ping
    envVars:
      - key: GPT_API_KEY
        sync: false
      - key: CRYPTOPANIC_API_KEY
        sync: false