from typing import Protocol
import pandas as pd


class Strategy(Protocol):
    """Protocol for strategy implementations."""

    def run(self, df: pd.DataFrame, config: dict) -> pd.DataFrame:
        """Run the strategy on OHLCV data.

        Parameters
        ----------
        df: pd.DataFrame
            DataFrame indexed by UTC timestamps with columns: Open, High, Low, Close, Volume.
        config: dict
            Strategy-specific configuration.

        Returns
        -------
        pd.DataFrame
            DataFrame containing at least the columns `Signal` and `Price` (Close),
            plus any indicator columns generated by the strategy.
        """
        ...
